spring:
  cloud:
    gateway:
      routes:
        # Route to the POST endpoint in lux-rest-app
        - id: foo-route
          uri: ${FOO_ROUTE_URI:http://localhost:8088}
          predicates:
            - Path=/foo
          filters:
            - PrefixPath=/api/v1
        # pre filter - logs all inbound requests for audit purposes
            - name: ScgPreFilterLogging
        # pre filter - validates jwt token
            - name: ScgPreFilterAuth
        # post filter - adds custom header
            - name: ScgPostFilterHeader
        # POST endpoint for generating jwt auth token
        - id: token-route
          uri: ${TOKEN_ROUTE_URI:http://localhost:8080}
          predicates:
            - Path=/token
  main:
    banner-mode: off
    log-startup-info: true

logging:
  level:
    org.apache.commons.httpclient: OFF
    org.springframework.cloud.gateway: OFF
    org.springframework.boot.web.embedded.netty: OFF
    org.springframework.security.core.userdetails: OFF
    org.springframework.cloud.context.scope: OFF
    reactor.netty.http.client: OFF
    com.sergeb.luxgatewayjava.filters: INFO
  pattern:
    console: '%d{HH:mm:ss.SSS} %highlight(%-5level) : %msg%n - %magenta([%thread]) %logger.%M'
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level : %msg%n - [%thread] %logger{36}.%M'
  file:
    name: "gateway.log"
    path: "c:\\temp\\GatewayLogs"
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
server:
  port: 8800
